# Generated by Django 3.1.3 on 2022-11-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dingdans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(blank=True, max_length=20, null=True)),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('dingdanname', models.CharField(blank=True, max_length=20, null=True)),
                ('upmoney', models.CharField(blank=True, max_length=20, null=True)),
                ('pi', models.CharField(blank=True, max_length=20, null=True)),
                ('com', models.CharField(blank=True, max_length=100, null=True)),
                ('dingdanID', models.CharField(blank=True, max_length=20, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('num', models.CharField(blank=True, max_length=20, null=True)),
                ('money', models.CharField(blank=True, max_length=20, null=True)),
                ('othermoney', models.CharField(blank=True, max_length=20, null=True)),
                ('allmoney', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
