# Generated by Django 3.1.3 on 2022-11-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_dingdans'),
    ]

    operations = [
        migrations.CreateModel(
            name='selectDingdans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(blank=True, max_length=20, null=True)),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('dingdanname', models.CharField(blank=True, max_length=20, null=True)),
                ('upmoney', models.CharField(blank=True, max_length=20, null=True)),
                ('pi', models.CharField(blank=True, max_length=20, null=True)),
                ('com', models.CharField(blank=True, max_length=100, null=True)),
                ('dingdanID', models.CharField(blank=True, max_length=20, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('num', models.CharField(blank=True, max_length=20, null=True)),
                ('money', models.CharField(blank=True, max_length=20, null=True)),
                ('othermoney', models.CharField(blank=True, max_length=20, null=True)),
                ('allmoney', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='dingdans',
            old_name='allmoney',
            new_name='goods',
        ),
        migrations.RenameField(
            model_name='dingdans',
            old_name='dingdanID',
            new_name='index',
        ),
        migrations.RenameField(
            model_name='dingdans',
            old_name='dingdanname',
            new_name='kehu',
        ),
        migrations.RenameField(
            model_name='dingdans',
            old_name='num',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='dingdans',
            old_name='othermoney',
            new_name='poID',
        ),
        migrations.RenameField(
            model_name='dingdans',
            old_name='time',
            new_name='poTime',
        ),
        migrations.RenameField(
            model_name='dingdans',
            old_name='type',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='dingdans',
            name='com',
        ),
        migrations.RemoveField(
            model_name='dingdans',
            name='upmoney',
        ),
        migrations.RemoveField(
            model_name='dingdans',
            name='username',
        ),
    ]
